Repository dev-FEFIVE/NadoCat, pull requests merged in 2024-08, with the labels that each got.

#18 Feat: Prisma 기본 설정
  server/client.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
Labels: 🐈‍⬛BE, ⚙️Setting

#20 Chore: server 및 client AWS 자동 배포 위한 설정 파일 작성
  client/package-lock.json
  client/package.json
  server/webhook.js
Labels: ⚙️Setting

#23 Feat: 회원가입 API 및 컨트롤러 구현
  server/controller/UserController.ts
  server/controller/sample.txt
  server/package-lock.json
  server/package.json
  server/routes/sample.txt
  server/routes/users.ts
Labels: 🐈‍⬛BE

#24 Feat: 동네 고양이 도감 API 틀 생성, testString 테이블 레코드 반환 쿼리 테스트
  server/controller/StreetCatsController.ts
  server/index.ts
  server/routes/streetCats.ts
Labels: 🐈‍⬛BE

#25 Feat: 커뮤니티 게시판 API 구현
  server/controller/Communities.ts
  server/prisma/schema.prisma
  server/routes/communities.ts
Labels: 🐈‍⬛BE

#27 Feat: setting.json 설정(Todo Tree), 동네 고양이 도감 API 구현중
  .vscode/settings.json
  server/controller/StreetCatsController.ts
  server/index.ts
Labels: 🐈‍⬛BE, ⚙️Setting

#31 Refactor: index.ts에 users 라우터 추가
  server/controller/UserController.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/routes/users.ts
Labels: 🐈‍⬛BE

#32 Rename: 커뮤니티 컨트롤러 파일명 변경
  server/controller/community/Communities.ts
  server/controller/community/CommunityComments.ts
  server/package-lock.json
Labels: 🐈‍⬛BE

#33 Refactor: 커뮤니티 댓글 DB 관련 부분 model 폴더로 코드 분리
  server/controller/community/CommunityComments.ts
  server/model/communityComment.model.ts
  server/routes/communities.ts
Labels: 🐈‍⬛BE

#34 Feat: 회원가입 prisma/bcrypt/uuid 적용
  server/controller/UserController.ts
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
Labels: 🐈‍⬛BE

#38 Fix: 동네 고양이 도감 uuid 타입, 관련 코드 수정, prisma-case-format 적용
  server/controller/StreetCatsController.ts
  server/controller/streetCat/StreetCats.ts
  server/controller/streetCat/StreetCatsComments.ts
  server/model/streetCat.model.ts
  server/routes/streetCats.ts
  server/types/streetCat.ts
Labels: 🐈‍⬛BE, 🧑‍💻Refactor

#43 Feat: 실종고양이 게시글 create, delete API
  server/.gitignore
  server/controller/missing/Missing.ts
  server/controller/missing/Missings.ts
  server/controller/missing/MissingsFavorites.ts
  server/model/location.model.ts
  server/model/missing.model.ts
  server/prisma/schema.prisma
  server/routes/missings.ts
  server/types/Missing.ts
  server/types/image.ts
  server/types/location.ts
Labels: 🐈‍⬛BE

#46 Feat: 친구 맺기 API, 이벤트/모임 게시글 목록 조회, 게시글 등록 API 구현
  server/controller/community/Communities.ts
  server/controller/community/CommunityComments.ts
  server/controller/event/events.ts
  server/controller/friend/friends.ts
  server/controller/missing/Missing.ts
  server/index.ts
  server/model/community.model.ts
  server/model/communityComment.model.ts
  server/model/friend.modle.ts
  server/model/image.model.ts
  server/model/tag.model.ts
  server/routes/events.ts
  server/routes/users.ts
Labels: 🐈‍⬛BE

#47 Rename: server/model/friend.modle.ts -> server/model/friend.model.ts 파일명 오타 수정
  server/controller/friend/friends.ts
  server/model/friend.model.ts
Labels: 🐈‍⬛BE

#51 Feat: 동네 고양이 도감 API 구현
  server/controller/streetCat/StreetCats.ts
  server/controller/streetCat/StreetCatsComments.ts
  server/controller/streetCat/StreetCatsFavorite.ts
  server/model/streetCat.model.ts
  server/routes/streetCats.ts
  server/routes/users.ts
Labels: 🐈‍⬛BE, ✨Feature

#52 Feat: 로그인 기능 추가
  client/src/pages/Login.tsx
  server/controller/user/MyPage.ts
  server/controller/user/Users.ts
  server/package-lock.json
  server/package.json
  server/routes/users.ts
  server/utils/auth.ts
Labels: 🐈‍⬛BE

#54 커뮤니티, 친구 맺기, 이벤트/모임 관련 에러 처리 부분 수정/ cors, morgan, helmet 설치/ 일부 파일명 변경
  server/controller/community/Communities.ts
  server/controller/community/CommunityComments.ts
  server/controller/event/EventComments.ts
  server/controller/event/Events.ts
  server/controller/friend/Friends.ts
  server/controller/missing/MissingReport.ts
  server/index.ts
  server/model/missing.model.ts
  server/package-lock.json
  server/package.json
  server/types/missing.ts
  server/util/errors/errors.ts
Labels: 🐈‍⬛BE, ⚙️Setting, 🧑‍💻Refactor

#57 Refactor: 회원가입 및 로그인 model분리, type생성, 자동로그인
  server/controller/user/MyPage.ts
  server/controller/user/Users.ts
  server/middleware/validator.ts
  server/model/user.model.ts
  server/routes/users.ts
  server/types/user.ts
  server/util/auth/auth.ts
Labels: 🐈‍⬛BE

#59 Refactor: 자동로그인 refresh token
  server/controller/user/Users.ts
  server/middleware/validator.ts
  server/model/user.model.ts
  server/routes/users.ts
Labels: 🐈‍⬛BE

#62 Feat: 로그인, 회원가입 FE작업 시작
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/user.api.ts
  client/src/components/user/Login.tsx
  client/src/components/user/Signup.tsx
  client/src/pages/user/Login.scss
  client/src/store/userStore.ts
Labels: 🐈FE

#63 Refactor: 로그인, 회원가입 수정
  client/src/pages/Login.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/Signup.tsx
Labels: 🐈FE

#64 Fix: @media 오류 수정
  client/src/components/common/Header.tsx
  client/src/styles/css/base/common.css
  client/src/styles/css/components/common/footer.css
  client/src/styles/css/components/common/header.css
  client/src/styles/css/components/layout/layout.css
  client/src/styles/css/pages/streetCat/streetCat.css
  client/src/styles/scss/base/common.scss
Labels: 🎨Design, 🧑‍💻Refactor

#66 Feat: 커뮤니티, 이벤트/모임 게시판 댓글 수정 및 FE 커뮤니티 게시판 페이지 추가
  client/src/App.tsx
  client/src/components/common/Header.tsx
  client/src/components/layout/Layout.tsx
  client/src/pages/community/community.tsx
  client/src/styles/scss/pages/community/community.scss
  server/model/communityComment.model.ts
  server/model/eventComment.model.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature

#69 Feat: 카카오 OAuth 작업중
  client/package-lock.json
  client/package.json
  client/src/api/http.ts
  client/src/api/sample.txt
  client/src/api/user.api.ts
  client/src/hooks/sample.txt
  client/src/hooks/useKakao.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/Signup.tsx
  client/src/store/sample.txt
  client/src/store/userStore.ts
  server/controller/user/Users.ts
  server/index.ts
  server/model/user.model.ts
  server/routes/users.ts
  server/utils/auth.ts
Labels: 🐈FE, 🐈‍⬛BE

#70 Design: 헤더/푸터 수정, reset.css, 동네 고양이 도감 목록UI
  client/src/App.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/Header.tsx
  client/src/pages/streetCat/StreetCat.tsx
  client/src/styles/css/base/common.css
  client/src/styles/css/base/common.css.map
  client/src/styles/css/base/normalize.css
  client/src/styles/css/base/reset.css
  client/src/styles/css/components/common/footer.css
  client/src/styles/css/components/common/footer.css.map
  client/src/styles/css/components/common/header.css
  client/src/styles/css/components/common/header.css.map
  client/src/styles/css/components/layout/layout.css
  client/src/styles/css/components/layout/layout.css.map
  client/src/styles/css/pages/streetCat/streetCat.css
  client/src/styles/css/pages/streetCat/streetCat.css.map
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/common/footer.scss
  client/src/styles/scss/components/common/header.scss
  client/src/styles/scss/components/layout/layout.scss
  client/src/styles/scss/pages/streetCat/streetCat.scss
Labels: 🎨Design

#72 Feat: kakao login client/server작업
  client/src/api/http.ts
  client/src/api/user.api.ts
  client/src/components/user/Login.tsx
  client/src/hooks/useKakao.ts
  client/src/pages/user/Login.tsx
  server/controller/user/Users.ts
  server/index.ts
  server/model/user.model.ts
  server/package-lock.json
  server/routes/users.ts
Labels: 🐈FE, 🐈‍⬛BE

#75 이미지 캐러셀 구현 및 favicon 변경 등
  client/index.html
  client/public/paw.svg
  client/src/components/common/ImageCarousel.tsx
  client/src/components/community/CommunityComments.tsx
  client/src/components/community/Post.tsx
  client/src/components/community/PostDetail.tsx
  client/src/models/community.model.ts
  client/src/models/image.model.ts
  client/src/pages/community/Community.tsx
  client/src/pages/community/CommunityDetail.tsx
  client/src/styles/css/base/common.css
  client/src/styles/css/base/common.css.map
  client/src/styles/css/components/common/footer.css
  client/src/styles/css/components/common/footer.css.map
  client/src/styles/css/components/common/header.css
  client/src/styles/css/components/common/header.css.map
  client/src/styles/css/components/common/imageCarousel.css
  client/src/styles/css/components/common/imageCarousel.css.map
  client/src/styles/css/components/common/tags.css
  client/src/styles/css/components/common/tags.css.map
  client/src/styles/css/components/community/avartar.css
  client/src/styles/css/components/community/avartar.css.map
  client/src/styles/css/components/community/comments.css
  client/src/styles/css/components/community/comments.css.map
  client/src/styles/css/components/community/commentsEmpty.css
  client/src/styles/css/components/community/commentsEmpty.css.map
  client/src/styles/css/components/community/post.css
  client/src/styles/css/components/community/post.css.map
  client/src/styles/css/components/community/postDetail.css
  client/src/styles/css/components/community/postDetail.css.map
  client/src/styles/css/components/community/postEmpty.css
  client/src/styles/css/components/community/postEmpty.css.map
  client/src/styles/css/components/community/postList.css
  client/src/styles/css/components/community/postList.css.map
  client/src/styles/css/components/error/errorNotFound.css
  client/src/styles/css/components/error/errorNotFound.css.map
  client/src/styles/css/components/error/notFound.css
  client/src/styles/css/components/error/notFound.css.map
  client/src/styles/css/components/layout/layout.css
  client/src/styles/css/components/layout/layout.css.map
  client/src/styles/css/pages/community/community.css
  client/src/styles/css/pages/community/community.css.map
  client/src/styles/css/pages/community/communityDetail.css
  client/src/styles/css/pages/community/communityDetail.css.map
  client/src/styles/css/pages/error/errorPage.css
  client/src/styles/css/pages/error/errorPage.css.map
  client/src/styles/css/pages/streetCat/streetCat.css
  client/src/styles/css/pages/streetCat/streetCat.css.map
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/common/header.scss
  client/src/styles/scss/components/common/imageCarousel.scss
  client/src/styles/scss/components/community/post.scss
  client/src/styles/scss/components/community/postDetail.scss
  client/src/styles/scss/components/error/notFound.scss
  client/src/styles/scss/components/layout/layout.scss
  client/src/styles/scss/pages/community/community.scss
  client/src/styles/scss/pages/community/communityDetail.scss
  server/model/notification.model.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature, 🧑‍💻Refactor

#77 Feat: 커뮤니티 게시판, 이벤트/모임 게시판 댓글 등록 기능 구현
  client/src/api/community.api.ts
  client/src/api/event.api.ts
  client/src/components/comment/CommentForm.tsx
  client/src/components/community/CommunityComments.tsx
  client/src/hooks/useCommunityComment.ts
  client/src/hooks/useEventComment.ts
  client/src/pages/community/CommunityDetail.tsx
  client/src/pages/event/EventDetail.tsx
  client/src/styles/css/components/comment/comment.css
  client/src/styles/css/components/comment/comment.css.map
  client/src/styles/scss/components/comment/comment.scss
  server/controller/community/CommunityComments.ts
  server/controller/event/EventComments.ts
  server/model/communityComment.model.ts
  server/model/eventComment.model.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature, 🧑‍💻Refactor

#80 Feat: 회원가입 프론트 작업 및 백 연결/auth.ts 미들웨어 분리
  client/package-lock.json
  client/package.json
  client/src/api/http.ts
  client/src/components/layout/Layout.tsx
  client/src/components/user/CustomModal.tsx
  client/src/components/user/InputText.tsx
  client/src/components/user/Signup.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/Signup.tsx
  client/src/styles/css/components/layout/layout.css
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/layout/layout.scss
  client/src/styles/scss/components/user/customModal.scss
  client/src/styles/scss/components/user/inputText.scss
  client/src/styles/scss/pages/user/login.scss
  client/src/styles/scss/pages/user/signup.scss
Labels: 🐈FE, 🐈‍⬛BE

#81 Feat: auth.ts 미들웨어 분리 시도/회원가입&로그인 수정
  client/src/api/user.api.ts
  client/src/pages/MyPage.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/Signup.tsx
  client/src/styles/scss/pages/user/login.scss
  client/src/styles/scss/pages/user/signup.scss
  server/controller/user/MyPage.ts
  server/controller/user/Users.ts
  server/middleware/auth.ts
  server/middleware/validator.ts
  server/model/user.model.ts
  server/routes/users.ts
  server/tsconfig.json
  server/types/express.d.ts
Labels: 🐈FE, 🐈‍⬛BE

#82 Feat: 동네 고양이 도감 FE 구현중
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/streetCat.api.ts
  client/src/assets/img/HiLocationMarker.png
  client/src/assets/img/deleteBtn.png
  client/src/assets/img/heartCat.png
  client/src/assets/img/locationMarker.png
  client/src/components/common/WriteButton.tsx
  client/src/components/streetCat/ImageUpload.tsx
  client/src/components/streetCat/MyStreetCatEmpty.tsx
  client/src/components/streetCat/MyStreetCatPosts.tsx
  client/src/components/streetCat/StreetCatPosts.tsx
  client/src/components/streetCat/StreetCatsMap.tsx
  client/src/components/streetCat/TabNavigation.tsx
  client/src/hooks/useStreetCat.ts
  client/src/hooks/useStreetCats.ts
  client/src/models/streetCat.model.ts
  client/src/pages/streetCat/StreetCat.tsx
  client/src/pages/streetCat/StreetCatDetail.tsx
  client/src/pages/streetCat/StreetCatWrite.tsx
  client/src/styles/css/base/common.css.map
  client/src/styles/css/components/common/writeButton.css
  client/src/styles/css/components/common/writeButton.css.map
  client/src/styles/css/components/streetCat/MyStreetCatEmpty.css
  client/src/styles/css/components/streetCat/MyStreetCatEmpty.css.map
  client/src/styles/css/components/streetCat/MyStreetCatPosts.css
  client/src/styles/css/components/streetCat/MyStreetCatPosts.css.map
  client/src/styles/css/components/streetCat/imageUpload.css
  client/src/styles/css/components/streetCat/imageUpload.css.map
  client/src/styles/css/components/streetCat/streetCatPosts.css
  client/src/styles/css/components/streetCat/streetCatPosts.css.map
  client/src/styles/css/components/streetCat/streetCatsMap.css
  client/src/styles/css/components/streetCat/streetCatsMap.css.map
  client/src/styles/css/components/streetCat/tabNavigation.css
  client/src/styles/css/components/streetCat/tabNavigation.css.map
  client/src/styles/css/pages/streetCat/streetCat.css.map
  client/src/styles/css/pages/streetCat/streetCatDetail.css
  client/src/styles/css/pages/streetCat/streetCatDetail.css.map
  client/src/styles/css/pages/streetCat/streetCatWrite.css
  client/src/styles/css/pages/streetCat/streetCatWrite.css.map
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/common/writeButton.scss
  client/src/styles/scss/components/streetCat/MyStreetCatEmpty.scss
  client/src/styles/scss/components/streetCat/MyStreetCatPosts.scss
  client/src/styles/scss/components/streetCat/imageUpload.scss
  client/src/styles/scss/components/streetCat/streetCatPosts.scss
  client/src/styles/scss/components/streetCat/streetCatsMap.scss
  client/src/styles/scss/components/streetCat/tabNavigation.scss
  client/src/styles/scss/pages/streetCat/streetCat.scss
  client/src/styles/scss/pages/streetCat/streetCatDetail.scss
  client/src/styles/scss/pages/streetCat/streetCatWrite.scss
  server/model/streetCat.model.ts
  server/prisma/schema.prisma
Labels: 🐈FE, ✨Feature

#85 Feat: 로그인&회원가입 자잘한 작업/마이페이지 프론트 작업 중
  client/src/App.tsx
  client/src/api/user.api.ts
  client/src/assets/img/profileCat.png
  client/src/assets/img/welcomeCat.png
  client/src/components/user/CustomModal.tsx
  client/src/components/user/Login.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/components/user/my/MyTab.tsx
  client/src/components/user/my/ProfileModal.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/My.tsx
  client/src/pages/user/Signup.tsx
  client/src/styles/css/components/layout/layout.css
  client/src/styles/scss/components/layout/layout.scss
  client/src/styles/scss/components/user/customModal.scss
  client/src/styles/scss/components/user/my/myInfo.scss
  client/src/styles/scss/components/user/my/myTab.scss
  client/src/styles/scss/components/user/my/profileModal.scss
  client/src/styles/scss/pages/user/login.scss
  client/src/styles/scss/pages/user/my.scss
  client/src/styles/scss/pages/user/signup.scss
Labels: 🐈FE

#87 Feat: 게시글 작성 버튼 및 게시글 작성 폼 업로더 컴포넌트 구현
  client/src/components/common/WriteButtonVer2.tsx
  client/src/components/communityAndEvent/ImageUploader.tsx
  client/src/pages/community/Community.tsx
  client/src/pages/community/CommunityPostWrite.tsx
  client/src/pages/event/Event.tsx
  client/src/styles/scss/components/common/newPostButton.scss
  client/src/styles/scss/components/communityAndEvent/imageUploader.scss
  client/src/styles/scss/pages/community/community.scss
  client/src/styles/scss/pages/community/communityPostWrite.scss
  client/src/styles/scss/pages/event/event.scss
Labels: 🐈FE

#88 Rename: WriteButtonVer2.tsx -> NewPostButton.tsx 파일명 변경
  client/src/components/common/NewPostButton.tsx
  client/src/pages/community/Community.tsx
  client/src/pages/event/Event.tsx
Labels: 🐈FE

#90 Design: 댓글 폼 좋아요 버튼 삭제
  client/src/components/comment/CommentForm.tsx
  client/src/styles/scss/components/comment/commentForm.scss
  server/prisma/schema.prisma
Labels: 🐈FE, 🎨Design

#98 Feat: 커뮤니티, 이벤트 게시판 게시글 목록 정렬 기능 추가 등
  client/src/components/communityAndEvent/PostEditForm.tsx
  client/src/components/communityAndEvent/PostList.tsx
  client/src/components/communityAndEvent/PostSortMenu.tsx
  client/src/components/communityAndEvent/PostWriteForm.tsx
  client/src/components/communityAndEvent/SortButton.tsx
  client/src/components/loading/Spinner.tsx
  client/src/hooks/useOutSideClick.ts
  client/src/pages/community/Community.tsx
  client/src/pages/event/Event.tsx
  client/src/styles/scss/components/common/newPostButton.scss
  client/src/styles/scss/components/communityAndEvent/postSortMenu.scss
  client/src/styles/scss/components/communityAndEvent/sortButton.scss
  client/src/styles/scss/components/loading/spinner.scss
  client/src/styles/scss/components/streetCat/imageUpload.scss
  client/src/styles/scss/pages/community/community.scss
  client/src/styles/scss/pages/community/communityPostWrite.scss
  client/src/styles/scss/pages/event/event.scss
  client/src/utils/sort/sortMenu.ts
  server/controller/likes/Likes.ts
  server/model/like.model.ts
  server/routes/likes.ts
Labels: 🐈FE, 🎨Design, 🧑‍💻Refactor

#99 Fix: 프로필 이미지 관련 수정
  client/src/components/common/Avartar.tsx
  client/src/styles/scss/components/comment/comment.scss
  client/src/styles/scss/components/common/actionBar.scss
  client/src/styles/scss/components/common/avartar.scss
Labels: 🐈FE, 🎨Design

#103 Feat: 검색 페이지 UI 및 일부 기능 구현
  client/src/App.tsx
  client/src/assets/img/unfindableCat.png
  client/src/components/common/Footer.tsx
  client/src/components/layout/LayoutRouter.ts
  client/src/components/streetCat/StreetCatPosts.tsx
  client/src/hooks/useCommunityComment.ts
  client/src/hooks/useDebounce.ts
  client/src/pages/community/Community.tsx
  client/src/pages/event/Event.tsx
  client/src/pages/search/RecentKeywords.tsx
  client/src/pages/search/Search.tsx
  client/src/styles/scss/components/communityAndEvent/post.scss
  client/src/styles/scss/components/streetCat/streetCatPosts.scss
  client/src/styles/scss/pages/search/search.scss
  client/src/utils/localStorage/localStorage.ts
  server/controller/community/Communities.ts
  server/controller/community/CommunityComments.ts
  server/controller/event/EventComments.ts
  server/model/communityComment.model.ts
  server/model/event.model.ts
  server/model/eventComment.model.ts
  server/package-lock.json
  server/routes/communities.ts
  server/types/event.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature, 🎨Design

#104 Fix: HeaderWithBackButton.tsx 수정 등
  client/src/App.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/HeaderWithBackButton.tsx
  client/src/components/communityAndEvent/PostMenu.tsx
  client/src/pages/community/CommunityPostEdit.tsx
  client/src/pages/event/EventPostWrite.tsx
  client/src/utils/boards/boards.ts
  server/model/interest.model.ts
Labels: 🐈FE, 🐈‍⬛BE, 🧑‍💻Refactor

#110 Design: 카테고리 페이지 UI 수정 등
  client/src/App.tsx
  client/src/assets/img/noBackgroundCat.png
  client/src/assets/img/noBackgroundCat2.png
  client/src/assets/img/speechBubble.png
  client/src/pages/boards/Boards.tsx
  client/src/pages/protectedPath/ProtectedPath.tsx
  client/src/styles/scss/pages/boards/boards.scss
  server/controller/community/Communities.ts
  server/controller/community/CommunityComments.ts
  server/controller/event/EventComments.ts
  server/controller/event/Events.ts
  server/controller/friend/Friends.ts
  server/controller/likes/Likes.ts
  server/controller/user/Users.ts
  server/model/community.model.ts
  server/model/event.model.ts
  server/model/friend.model.ts
  server/model/like.model.ts
  server/routes/communities.ts
  server/routes/events.ts
Labels: 🐈FE, 🐈‍⬛BE, 🎨Design, 🧑‍💻Refactor

#113 Feat: token 로컬스토리지 방식에서 http-only방식으로 변경
  client/src/api/http.ts
  client/src/api/user.api.ts
  client/src/components/user/UserInfo.tsx
  client/src/components/user/my/Logout.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/My.tsx
  client/src/store/userStore.ts
  client/src/styles/scss/components/user/my/myInfo.scss
  client/src/styles/scss/pages/user/login.scss
  server/controller/user/MyPage.ts
  server/controller/user/Users.ts
  server/index.ts
  server/middleware/auth.ts
  server/model/image.model.ts
  server/model/my.model.ts
  server/model/user.model.ts
  server/package-lock.json
  server/package.json
  server/routes/users.ts
  server/types/image.ts
  server/util/images/addNewImages.ts
  server/util/images/deleteImages.ts
Labels: 🐈FE, 🐈‍⬛BE

#126 Feat: 커뮤니티, 이벤트 게시판 목록 정렬 로컬스토리지 방식 구현 등
  client/src/App.tsx
  client/src/api/friend.apit.ts
  client/src/components/comment/CommentError.tsx
  client/src/components/common/Header.tsx
  client/src/components/community/CommunityComments.tsx
  client/src/components/communityAndEvent/PostEmpty.tsx
  client/src/components/communityAndEvent/PostMenu.tsx
  client/src/components/communityAndEvent/SortButton.tsx
  client/src/components/event/EventComments.tsx
  client/src/components/friend/Friend.tsx
  client/src/components/friend/FriendList.tsx
  client/src/components/notifications/NotificationAlarm.tsx
  client/src/hooks/useFriend.ts
  client/src/hooks/useFriends.ts
  client/src/models/friend.model.ts
  client/src/pages/community/Community.tsx
  client/src/pages/event/Event.tsx
  client/src/pages/user/Friends.tsx
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/communityAndEvent/postMenu.scss
  client/src/styles/scss/components/notification/notificationAlarm.scss
  client/src/styles/scss/pages/friends/friends.scss
  client/src/utils/localStorage/localStorage.ts
  server/controller/community/Communities.ts
  server/controller/event/Events.ts
  server/controller/friend/Friends.ts
  server/model/event.model.ts
  server/util/sort/orderBy.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature, 🎨Design

#127 Fix: 이벤트 게시판 게시글 수정 버그 수정
  server/controller/event/Events.ts
Labels: 🐈‍⬛BE

#128 Fix: 동네 고양이 도감 탭 분리, uuid로 기능 점검 및 수정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/streetCat.api.ts
  client/src/components/common/FavoriteButton.tsx
  client/src/components/streetCat/CommentForm.tsx
  client/src/components/streetCat/MyStreetCatPosts.tsx
  client/src/components/streetCat/PostDetail.tsx
  client/src/components/streetCat/StreetCatComments.tsx
  client/src/components/streetCat/StreetCatPosts.tsx
  client/src/components/streetCat/TabNavigation.tsx
  client/src/hooks/useMyStreetCats.ts
  client/src/hooks/useStreetCat.ts
  client/src/hooks/useStreetCats.ts
  client/src/pages/streetCat/StreetCat.tsx
  client/src/pages/streetCat/StreetCatDetail.tsx
  client/src/pages/streetCat/StreetCatEdit.tsx
  client/src/pages/streetCat/StreetCatWrite.tsx
  client/src/styles/scss/components/streetCat/MyStreetCatPosts.scss
  client/src/styles/scss/components/streetCat/calendar.scss
  client/src/styles/scss/components/streetCat/streetCatPosts.scss
  client/src/styles/scss/pages/boards/boards.scss
  client/src/styles/scss/pages/streetCat/streetCatDetail.scss
  server/controller/streetCat/StreetCats.ts
  server/controller/streetCat/StreetCatsComments.ts
  server/controller/streetCat/StreetCatsFavorite.ts
  server/model/streetCat.model.ts
Labels: 🐈FE, ✨Feature, 🧑‍💻Refactor

#131 Feat: 마이페이지 친구 목록 조회 기능 추가
  client/src/App.tsx
  client/src/components/user/my/MyTab.tsx
  client/src/hooks/useFriends.ts
  client/src/pages/user/Friends.tsx
  client/src/pages/user/My.tsx
  client/src/styles/scss/components/user/my/myTab.scss
  client/src/styles/scss/pages/friends/friends.scss
Labels: 🐈FE, ✨Feature, 🎨Design

#132 Fix: 친구 목록 오류 수정 등
  client/src/components/friend/FriendList.tsx
  client/src/hooks/useCommunities.ts
  client/src/hooks/useCommunityComment.ts
  client/src/hooks/useEventComment.ts
  client/src/hooks/useEvents.ts
  client/src/hooks/useFriends.ts
Labels: 🐈FE

#133 Feature: 마이페이지 Setting 기능 완료
  client/src/App.tsx
  client/src/api/user.api.ts
  client/src/components/common/ActionBar.tsx
  client/src/components/common/Footer.tsx
  client/src/components/communityAndEvent/PostMenu.tsx
  client/src/components/layout/LayoutRouter.ts
  client/src/components/user/UserInfo.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/components/user/my/SettingAuthPassword.tsx
  client/src/components/user/my/SettingDetail.tsx
  client/src/components/user/my/SettingNickname.tsx
  client/src/components/user/my/SettingPassword.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/My.tsx
  client/src/pages/user/Setting.tsx
  client/src/store/userStore.ts
  client/src/styles/scss/components/user/my/myInfo.scss
  client/src/styles/scss/components/user/my/myTab.scss
  client/src/styles/scss/components/user/my/settingAuthPassword.scss
  client/src/styles/scss/components/user/my/settingDetail.scss
  client/src/styles/scss/components/user/my/settingNickname.scss
  client/src/styles/scss/components/user/my/settingPassword.scss
  client/src/styles/scss/pages/user/login.scss
  client/src/styles/scss/pages/user/my.scss
  client/src/styles/scss/pages/user/setting.scss
  client/src/styles/scss/pages/user/signup.scss
  server/controller/user/MyPage.ts
  server/controller/user/Users.ts
  server/model/my.model.ts
  server/model/user.model.ts
  server/routes/users.ts
Labels: 🐈FE, 🐈‍⬛BE

#137 Feat: 최근 검색어 중복 저장 방지 및 최근 검색어 선택 검색 추가 등
  client/src/components/home/TopBenner.tsx
  client/src/pages/search/RecentKeywords.tsx
  client/src/pages/search/Search.tsx
  client/src/styles/scss/components/common/embla.scss
  client/src/styles/scss/pages/search/search.scss
Labels: 🐈FE, ✨Feature, 🎨Design

#138 Fix: 이벤트, 커뮤니티 게시판 글쓰기 오류 수정 등
  client/src/hooks/useCommunities.ts
  client/src/hooks/useEvents.ts
  client/src/pages/community/CommunityPostWrite.tsx
  client/src/pages/event/EventPostWrite.tsx
  server/controller/streetCat/StreetCats.ts
  server/controller/streetCat/StreetCatsFavorite.ts
  server/routes/streetCats.ts
  server/routes/users.ts
Labels: 🐈FE, 🐈‍⬛BE

#139 Feat: 동네 고양이 지도 기능 구현(고정값)
  client/src/App.tsx
  client/src/api/streetCat.api.ts
  client/src/components/streetCat/DiscoveryLocation.tsx
  client/src/components/streetCat/StreetCatPosts.tsx
  client/src/components/streetCat/StreetCatsMap.tsx
  client/src/hooks/useStreetCat.ts
  client/src/pages/streetCat/StreetCatDetail.tsx
  client/src/styles/scss/components/streetCat/MyStreetCatPosts.scss
  client/src/styles/scss/components/streetCat/streetCatPosts.scss
  server/controller/streetCat/StreetCats.ts
  server/model/streetCat.model.ts
  server/routes/streetCats.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature

#140 Fix: 동네 고양이 도감 컴포넌트 수정
  client/src/components/streetCat/StreetCatPosts.tsx
Labels: 🐈FE

#141 Feat: Post.tsx 클릭시 이동 경로 관련 함수 추가 등
  client/src/assets/img/delete_button.svg
  client/src/components/common/ImageCarousel.tsx
  client/src/components/communityAndEvent/Post.tsx
  client/src/components/home/TopBenner.tsx
  client/src/styles/scss/components/common/imageCarousel.scss
  client/src/styles/scss/pages/home/home.scss
Labels: 🐈FE, ✨Feature, 🎨Design

#142 Feat: 친구 맺기 및 삭제 버튼 및 기능 구현 등
  client/src/api/friend.apit.ts
  client/src/components/communityAndEvent/Post.tsx
  client/src/components/friend/Friend.tsx
  client/src/components/friend/FriendButton.tsx
  client/src/components/home/HomeCommunitiesAndEvents.tsx
  client/src/components/home/HomeCommunity.tsx
  client/src/components/home/HomeEvent.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/hooks/useFriend.ts
  client/src/hooks/useFriends.ts
  client/src/pages/user/Friends.tsx
  client/src/styles/scss/components/friend/friendButton.scss
  server/controller/friend/Friends.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature, 🎨Design

#143 Fix: 친구 맺기 관련 API 수정
  server/model/friend.model.ts
  server/routes/users.ts
Labels: 🐈‍⬛BE

#145 Feat: 자동로그인&로그아웃 기능 개발/로컬에서 세션으로 스토리지 변경
  client/src/api/http.ts
  client/src/api/user.api.ts
  client/src/components/chat/ChatList.tsx
  client/src/components/chat/Message.tsx
  client/src/components/chat/Messages.tsx
  client/src/components/communityAndEvent/PostMenu.tsx
  client/src/components/user/CustomModal.tsx
  client/src/components/user/my/Logout.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/pages/chat/Chat.tsx
  client/src/pages/chat/ChatList.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/user/My.tsx
  client/src/pages/user/Signup.tsx
  client/src/store/userStore.ts
  client/src/styles/scss/components/user/customModal.scss
  server/controller/user/Users.ts
  server/middleware/auth.ts
  server/model/user.model.ts
Labels: 🐈FE, 🐈‍⬛BE

#147 Feat: 동네 고양이 지도 기능 고도화
  client/src/api/streetCat.api.ts
  client/src/components/comment/Comment.tsx
  client/src/components/common/FavoriteButton.tsx
  client/src/components/common/LoginModal.tsx
  client/src/components/streetCat/Author.tsx
  client/src/components/streetCat/PostDetail.tsx
  client/src/components/streetCat/StreetCatComments.tsx
  client/src/components/streetCat/StreetCatPosts.tsx
  client/src/components/streetCat/StreetCatsMap.tsx
  client/src/components/streetCat/streetCatComment.tsx
  client/src/hooks/useStreetCat.ts
  client/src/hooks/useStreetCatComments.ts
  client/src/models/streetCat.model.ts
  client/src/pages/streetCat/StreetCatDetail.tsx
  client/src/styles/scss/components/common/loginModal.scss
  client/src/styles/scss/components/communityAndEvent/imageUploader.scss
  client/src/styles/scss/components/streetCat/author.scss
  server/controller/streetCat/StreetCats.ts
  server/controller/streetCat/StreetCatsComments.ts
  server/controller/streetCat/StreetCatsFavorite.ts
  server/model/streetCat.model.ts
Labels: 🐈FE, 🐈‍⬛BE, ✨Feature

#154 Feat: index.html 설정 변경, 실종게시판 글쓰기ui 수정, 실종게시판 지도 마커 변경
  client/index.html
  client/src/components/common/MapBox.tsx
  client/src/components/missing/MissingWriteForm.tsx
  client/src/components/missing/reportPost/CustomSelect.tsx
  client/src/components/streetCat/MyStreetCatPosts.tsx
  client/src/components/streetCat/PostDetail.tsx
  client/src/components/streetCat/SerachMap.tsx
  client/src/components/streetCat/StreetCatComments.tsx
  client/src/components/streetCat/StreetCatsMap.tsx
  client/src/components/streetCat/streetCatComment.tsx
  client/src/pages/streetCat/StreetCatDetail.tsx
  client/src/styles/scss/components/common/loginModal.scss
  client/src/styles/scss/components/missing/customSelect.scss
  client/src/styles/scss/pages/missing/missingWriteForm.scss
  server/controller/streetCat/StreetCatsFavorite.ts
  server/model/streetCat.model.ts
Labels: 🐈FE, ✨Feature, 🎨Design

#155 Feat: 홈 UI 일부 추가 구현 등
  client/public/bg.webp
  client/src/assets/banner/banner1.png
  client/src/assets/banner/banner2.png
  client/src/assets/banner/banner3.png
  client/src/assets/img/pawLogo.png
  client/src/assets/img/welcomeCat2.png
  client/src/components/common/HomeCat.tsx
  client/src/components/home/HomeMissings.tsx
  client/src/components/home/MiddleBanner.tsx
  client/src/components/home/TopBenner.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/missing/MissingReportPost.tsx
  client/src/pages/Home/Home.tsx
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/common/footer.scss
  client/src/styles/scss/components/common/homeCat.scss
  client/src/styles/scss/components/common/newPostButton.scss
  client/src/styles/scss/components/layout/layout.scss
  client/src/styles/scss/components/loading/loadingCat.scss
  client/src/styles/scss/components/missing/missingReportPost.scss
  client/src/styles/scss/components/missing/postHead.scss
  client/src/styles/scss/pages/home/home.scss
  client/src/styles/scss/pages/user/login.scss
Labels: 🐈FE, ✨Feature, 🎨Design

#157 Refac: 마이페이지 my/user에 따라 버튼노출 조건부렌더링/회원탈퇴 기능/마이페이지에 관심글 조회가능하게 수정
  client/src/App.tsx
  client/src/api/user.api.ts
  client/src/components/communityAndEvent/PostMenu.tsx
  client/src/components/friend/FriendButton.tsx
  client/src/components/mypage/Posts.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/user/My.tsx
  client/src/pages/user/Setting.tsx
  client/src/styles/scss/components/chat/MessageBox.scss
  client/src/styles/scss/components/friend/friendButton.scss
  client/src/styles/scss/components/user/customModal.scss
  client/src/styles/scss/components/user/my/myInfo.scss
  client/src/styles/scss/pages/chat/Chat.scss
  server/controller/interest/Interests.ts
  server/controller/user/MyPage.ts
  server/controller/user/Users.ts
  server/index.ts
  server/model/my.model.ts
  server/routes/interest.ts
  server/routes/users.ts
Labels: 🐈FE, 🐈‍⬛BE

#172 Fix: 배경 고양이 이미지 UI 변경 등
  client/src/assets/img/home.png
  client/src/components/common/HomeCat.tsx
  client/src/pages/missing/Missings.tsx
  client/src/styles/scss/base/common.scss
  client/src/styles/scss/components/common/footer.scss
  client/src/styles/scss/components/common/homeCat.scss
  client/src/styles/scss/components/common/newPostButton.scss
  client/src/styles/scss/pages/missing/missing.scss
Labels: 🐈FE, 🎨Design

#177 fix: FE 빌드 오류 수정
  client/src/components/user/my/MyPosts.tsx
  client/src/pages/user/KakaoRedirect.tsx
  server/prisma/schema.prisma
Labels: 🐈FE

#178 Fix: 마이페이지 관심글, 작성한글 UI 수정
  client/src/components/mypage/Posts.tsx
  client/src/components/user/my/MyPosts.tsx
Labels: 🐈FE, ✨Feature, 🎨Design

#191 Feature: uuid session storage저장방식에서 redis저장으로 변경
  client/src/api/http.ts
  client/src/api/user.api.ts
  client/src/components/chat/ChatList.tsx
  client/src/components/chat/Message.tsx
  client/src/components/chat/Messages.tsx
  client/src/components/common/ActionBar.tsx
  client/src/components/common/Footer.tsx
  client/src/components/missing/MissingReportPost.tsx
  client/src/components/user/my/MyInfo.tsx
  client/src/pages/chat/Chat.tsx
  client/src/pages/chat/ChatList.tsx
  client/src/pages/user/KakaoRedirect.tsx
  client/src/pages/user/Login.tsx
  client/src/pages/user/My.tsx
  client/src/store/userStore.ts
  server/controller/user/Users.ts
  server/middleware/auth.ts
  server/model/user.model.ts
  server/redis.ts
  server/routes/users.ts
Labels: 🐈FE, 🐈‍⬛BE
